"""fix: add chunk_metadata jsonb to chunks

Revision ID: d29183662a0c
Revises: 5637a8185580
Create Date: 2025-05-12 13:37:30.597523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd29183662a0c'
down_revision: Union[str, None] = '5637a8185580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('chunk_meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    # удаляем, только если колонка реально есть
    op.execute("ALTER TABLE chunks DROP COLUMN IF EXISTS influence_method")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('influence_method', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('chunks', 'chunk_meta_data')
    # ### end Alembic commands ###
